<?php


namespace console\controllers;


use SensioLabs\Consul\ConsulResponse;
use  SensioLabs\Consul\ServiceFactory;
use SensioLabs\Consul\Services\AgentInterface;
use SensioLabs\Consul\Services\CatalogInterface;
use SensioLabs\Consul\Services\HealthInterface;
use SensioLabs\Consul\Services\KVInterface;
use yii\console\Controller;

class ConsulController extends Controller {
    /**
     * @var ServiceFactory
     */
    private $sf;

    /**
     * @var AgentInterface $agent
     */
    private $agent;

    /**
     * @var CatalogInterface
     */
    private $catalog;

    /**
     * @var HealthInterface
     */
    private $health;

    /**
     * @var KVInterface
     */
    private $kv;


    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sf = new ServiceFactory([
            'base_uri' => 'http://172.17.0.2:8500',
        ]);
        $this->agent = $this->sf->get(AgentInterface::class);
        $this->catalog = $this->sf->get(CatalogInterface::class);
        $this->health = $this->sf->get(HealthInterface::class);
        $this->kv = $this->sf->get(KVInterface::class);

    }

    public function actionServices() {
        $rsp = $this->agent->services();
        print_r($rsp->json());
    }

    public function actionQuery(){
        $rsp = $this->catalog->service('web')->json();
        print_r($rsp);
    }

    public function actionReg() {
        $rsp = $this->catalog->register([

        ]);
        print_r($rsp);
    }

    public function actionHeath() {
        $rsp = $this->health->service('web', ['passing' => true])->json();
        print_r($rsp);
    }

    public function actionPut() {
        $rsp = $this->kv->put('web/fp/redis', '123')->json();
        print_r($rsp);
        $rsp = $this->kv->put('web/fp/mysql', '199.168.0.1:3306')->json();
        print_r($rsp);
    }

    public function actionGet() {
        $rsp = $this->kv->get('web/fp/redis')->json();
        $rsp[0]['Value'] = base64_decode($rsp[0]['Value']);
        print_r($rsp);
        $rsp = $this->kv->get('web/fp/mysql')->json();
        $rsp[0]['Value'] = base64_decode($rsp[0]['Value']);
        print_r($rsp);
    }

    public function actionKvDel() {
        $rsp = $this->kv->delete('web/fp/redis')->json();
        print_r($rsp);
        $rsp = $this->kv->delete('web/fp/mysql')->json();
        print_r($rsp);
    }
}