<?php

namespace yii2\swoole_async\basic;

use Yii;
use yii\base\BaseObject;
use yii2\swoole_async\models\DB;
use yii2\swoole_async\models\Mysql;

/**
 *
 */
abstract class AsyncTask extends BaseObject
{
    /**
     * @var int
     */
    public $taskId;

    /**
     * @var Rule
     */
    public $rule;

    /**
     * @var string
     */
    public $ruleClass = 'yii2\swoole_async\basic\Rule';

    /**
     * @var DB
     */
    public $db = 'yii2\swoole_async\models\Mysql';

    /**
     * @var string
     */
    private $name;

    /**
     * @var array
     */
    public $data;

    /**
     * @var Swoole
     */
    public $swoole = 'swoole';

    /**
     * 订单时间最大值(目前最大只支持1天)
     * @var int
     */
    private $maxInterval = 86400000;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->rule)){
            self::showError("未配置rule参数!");
        } elseif (!is_object($this->rule)){
            if (!isset($this->rule['class'])){
                $this->rule['class']  = $this->ruleClass;
            }
            $this->rule = Yii::createObject($this->rule);
            if (!$this->rule->validate()){
                self::showError(current($this->rule->getFirstErrors()));
            }
        }
        $this->name = $this->getTaskName();
        $this->swoole = Yii::$app->get("swoole");
    }


    /**
     * 查询任务
     * @param int $taskId
     * @return AsyncTask
     */
    public static function findById(int $taskId):AsyncTask
    {
        // TODO: implement here
        $model = Mysql::findTask($taskId);
        if (empty($model)){
            self::showError("不存在的任务:{$taskId}");
        }
        return self::loadTask($model);
    }

    /**
     * 加载未完成的任务
     * @param Mysql $model
     * @return static
     */
    private static function loadTask($model)
    {
        $cnf = [
            'class' => $model->getTaskClass(),
            'taskId' => $model->getTaskId(),
            'data' => json_decode($model->getData(), true),
            'rule' => Yii::createObject(json_decode($model->getRule(), true)),
            'db' => $model,
        ];
        $task = Yii::createObject($cnf);

        return $task;
    }

    /**
     * @return AsyncTask[]
     */
    public static function findAllForLoading()
    {
        $all = [];
        $list = Mysql::findAllForLoading();
        foreach ($list as $item){
            $all[] = self::loadTask($item);
        }
        return $all;
    }

    /**
     * 消费任务
     * @param mixed $data
     * @return bool
     */
    public abstract function consume($data):bool;

    /**
     * 任务标识为已完成
     * @return bool
     */
    private function taskFinished():bool
    {
        // TODO: implement here
        return $this->db->taskFinished();
    }

    /**
     * 任务标识为需要继续执行
     * @return bool
     */
    public function taskContinue():bool
    {
        // TODO: implement here
        return $this->db->taskContinue();
    }

    /**
     * 获取任务名
     * @return string
     */
    public function getTaskName():string
    {
        if (!$this->name){
            $this->name = lcfirst((new \ReflectionClass($this))->getShortName());
        }

        return $this->name;
    }

    /**
     * 获取任务运行次数
     * @return int
     */
    public function getTaskRunCount():int
    {
        // TODO: implement here
        return $this->db->getRunCount();
    }

    /**
     * 抛出异常
     * @param $msg
     * @throws TaskException
     */
    public static function showError($msg)
    {
        throw new TaskException($msg);
    }

    /**
     * 生成任务数据
     * @param array $data
     * @return static
     */
    public static function generate($data)
    {
        if (!is_array($data)){
            self::showError("data参数必须是数组");
        }

        if (isset($data['taskId'])){
            self::showError("不允许配置task id");
        }

        $cnf = [
            'class' => get_called_class(),
            'data' => $data,
        ];

        /** @var static $task */
        $task = Yii::createObject($cnf);

        $config = [
            'task_class' => $cnf['class'],
            'task_name' => $task->getTaskName(),
            'task_data' => $task->toStr($task->data),
            'task_rule' => $task->rule->toJson(),
        ];


        if(!($model = $task->db::generate($config, $msg))){
            self::showError($msg);
        }

        Yii::info(["generate_task" => $config, 'id' => $model->getTaskId()]);
        $task->taskId = $model->getTaskId();
        $task->db = $model;

        return $task;
    }

    /**
     * 标识任务已完成
     * @return  bool
     */
    public function taskIsFinish()
    {
        return $this->db->isFinish();
    }

    /**
     * 转json
     * @param $mixed
     * @return string
     */
    private function toStr($mixed)
    {
        return is_array($mixed) ? json_encode($mixed, JSON_UNESCAPED_UNICODE) : $mixed;
    }

    /**
     * 任务标记为已超出最大运行次数（不会再执行）
     * @return bool
     */
    public function taskOver()
    {
        $this->beforeTaskOver($this->data);
        $res =  $this->db->taskOver();
        $this->afterTaskOver($this->data);
        return $res;
    }

    /**
     * 查询任务标是否已超出最大运行次数
     * @return bool
     */
    public function taskIsOver()
    {
        return $this->db->isOver();
    }


    /**
     * 计算任务下次运行的间隔
     * @return array
     */
    public function getInterval()
    {
        if ($this->taskIsFinish() || $this->taskIsOver()){
            return [false, false];
        }

        if($this->rule->isAsync()){
            return[2000, false];
        }

        list($firstInterval, $nextInterval) = $this->rule->getInterval($this);

        if ($firstInterval === false){
            return [false, false];
        }

        if ($firstInterval > $this->maxInterval || $nextInterval > $this->maxInterval){
            self::showError("延迟任务最长时间不能超过1天");
        }

        if ($this->rule->isDelay()){
            if ($firstInterval < 3000){ //解决数据库查询不到任务的问题
                $firstInterval = 3000;
            }

            return [$firstInterval, false];
        }

        if ($this->rule->isTimed()){
            if ($nextInterval){
                return [$firstInterval, $nextInterval];
            } else {
                return [$firstInterval, false];
            }
        }

        self::showError("无法解析(任务：$this->taskId)定时器时间间隔!");

    }

    /**
     * 执行任务
     * @return bool
     * @throws \Exception
     */
    public function run()
    {
        if ($this->taskIsFinish() || $this->taskIsOver()){
            return true;
        }

        try{
            $result = $this->consume($this->data);
            $this->taskLogic($result);
        }catch (\Exception $exception){
            $this->taskLogic(false);
            throw $exception;
        }
    }

    private function taskLogic($result)
    {
        if($this->rule->isAsync()){
            $this->taskFinished();
            return true;
        }

        if ($this->rule->isDelay() && true === $result) {
            $this->taskFinished();
        } else {
            $this->taskContinue();
        }
    }

    /**
     * 任务超出运行前的回调函数
     * @param array $data
     */
    public function beforeTaskOver($data)
    {

    }


    /**
     * 任务超出运行后的回调函数
     * @param array $data
     */
    public function afterTaskOver($data)
    {

    }

    public static function publish($data = [])
    {
        /** @var Swoole $swoole */
        $swoole = Yii::$app->get("swoole");
        $swoole->publish(self::generate($data));
    }

    public function forPut(): string
    {

    }
}
